name    'puppet-mesos'
version '0.0.1'
source 'UNKNOWN'
author 'Tomas Barton'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

dependency 'puppetlabs/stdlib', '>= 0.1.6'
