name    'deric-mesos'
version '0.3.0'
source 'http://github.com/deric/puppet-mesos'
author 'Tomas Barton'
license 'Apache License, Version 2.0'
summary 'Module managing Mesos master and slave instalation'
description 'Apache Mesos is a cluster manager that provides efficient resource isolation and sharing across distributed applications'
project_page 'http://github.com/deric/puppet-mesos'

dependency 'puppetlabs/stdlib', '>= 0.1.6'
